"""
Week 3 — Full ASX 200 Watchlist.

Sourced from State Street's SPDR S&P/ASX 200 ETF (STW) daily holdings file,
as of 17-Jun-2026 (https://www.ssga.com — STW fund holdings download).
This is the actual current index basket, not a stale or manually-curated list.

201 holdings included (the ASX 200 does not always hold exactly 200 names;
STW's basket totals 99.99% weight across these 201 equities once cash and
futures positions are excluded).

NOTE: This list will drift out of date as the index rebalances quarterly
(March/June/September/December). Refresh periodically by re-downloading the
STW holdings file from ssga.com and re-running the conversion script.

Each entry: ticker (EODHD format, <CODE>.AU), name, sector, and the STW
weight (%) at time of sourcing — included for reference/sanity-checking,
not used directly in distress calculations.
"""

ASX_200_WATCHLIST = [
    {'ticker': 'BHP.AU', 'name': 'Bhp Group Ltd', 'sector': 'Materials', 'weight_pct': 12.2139},
    {'ticker': 'CBA.AU', 'name': 'Cmnwlth Bk Of Aust', 'sector': 'Financials', 'weight_pct': 10.0421},
    {'ticker': 'WBC.AU', 'name': 'Westpac Bkg Corp', 'sector': 'Financials', 'weight_pct': 4.4694},
    {'ticker': 'NAB.AU', 'name': 'Natl Australia Bk', 'sector': 'Financials', 'weight_pct': 4.2356},
    {'ticker': 'ANZ.AU', 'name': 'Anz Group Hldgs Li', 'sector': 'Financials', 'weight_pct': 3.8691},
    {'ticker': 'WES.AU', 'name': 'Wesfarmers Ltd', 'sector': 'Consumer Discretionary', 'weight_pct': 3.5486},
    {'ticker': 'MQG.AU', 'name': 'Macquarie Gp Ltd', 'sector': 'Financials', 'weight_pct': 3.2758},
    {'ticker': 'RIO.AU', 'name': 'Rio Tinto Limited', 'sector': 'Materials', 'weight_pct': 2.5568},
    {'ticker': 'GMG.AU', 'name': 'Goodman Group', 'sector': 'Real Estate', 'weight_pct': 2.4468},
    {'ticker': 'TLS.AU', 'name': 'Telstra Group Ltd', 'sector': 'Communication Services', 'weight_pct': 2.1135},
    {'ticker': 'WDS.AU', 'name': 'Woodside Energy Gr', 'sector': 'Energy', 'weight_pct': 2.0118},
    {'ticker': 'CSL.AU', 'name': 'Csl Ltd', 'sector': 'Health Care', 'weight_pct': 1.9019},
    {'ticker': 'TCL.AU', 'name': 'Transurban Group', 'sector': 'Industrials', 'weight_pct': 1.7144},
    {'ticker': 'WOW.AU', 'name': 'Woolworths Grp Ltd', 'sector': 'Consumer Staples', 'weight_pct': 1.695},
    {'ticker': 'QBE.AU', 'name': 'Qbe Ins Group', 'sector': 'Financials', 'weight_pct': 1.3093},
    {'ticker': 'FMG.AU', 'name': 'Fortescue Ltd', 'sector': 'Materials', 'weight_pct': 1.2403},
    {'ticker': 'ALL.AU', 'name': 'Aristocrat Leisure', 'sector': 'Consumer Discretionary', 'weight_pct': 1.2193},
    {'ticker': 'NST.AU', 'name': 'Nthn Star Res Ltd', 'sector': 'Materials', 'weight_pct': 1.1376},
    {'ticker': 'COL.AU', 'name': 'Coles Group Ltd', 'sector': 'Consumer Staples', 'weight_pct': 1.1281},
    {'ticker': 'EVN.AU', 'name': 'Evolution Mining', 'sector': 'Materials', 'weight_pct': 1.0098},
    {'ticker': 'BXB.AU', 'name': 'Brambles Ltd', 'sector': 'Industrials', 'weight_pct': 0.9405},
    {'ticker': 'STO.AU', 'name': 'Santos Limited', 'sector': 'Energy', 'weight_pct': 0.8714},
    {'ticker': 'SUN.AU', 'name': 'Suncorp Group Ltd', 'sector': 'Financials', 'weight_pct': 0.7369},
    {'ticker': 'SCG.AU', 'name': 'Scentre Group Ltd', 'sector': 'Real Estate', 'weight_pct': 0.7346},
    {'ticker': 'CPU.AU', 'name': 'Computershare Ltd', 'sector': 'Industrials', 'weight_pct': 0.7339},
    {'ticker': 'S32.AU', 'name': 'South32 Ltd', 'sector': 'Materials', 'weight_pct': 0.7152},
    {'ticker': 'PLS.AU', 'name': 'Pls Group Limited', 'sector': 'Materials', 'weight_pct': 0.7051},
    {'ticker': 'IAG.AU', 'name': 'Insurance Aust Grp', 'sector': 'Financials', 'weight_pct': 0.7004},
    {'ticker': 'ORG.AU', 'name': 'Origin Energy', 'sector': 'Utilities', 'weight_pct': 0.6892},
    {'ticker': 'LYC.AU', 'name': 'Lynas Rare Earths', 'sector': 'Materials', 'weight_pct': 0.6147},
    {'ticker': 'SIG.AU', 'name': 'Sigma Healthcare L', 'sector': 'Health Care', 'weight_pct': 0.5952},
    {'ticker': 'RMD.AU', 'name': 'Resmed Inc', 'sector': 'Health Care', 'weight_pct': 0.5798},
    {'ticker': 'SOL.AU', 'name': 'Washington H Soul', 'sector': 'Financials', 'weight_pct': 0.5775},
    {'ticker': 'QAN.AU', 'name': 'Qantas Airways', 'sector': 'Industrials', 'weight_pct': 0.5525},
    {'ticker': 'BSL.AU', 'name': 'Bluescope Steel', 'sector': 'Materials', 'weight_pct': 0.5513},
    {'ticker': 'APA.AU', 'name': 'Apa Group', 'sector': 'Utilities', 'weight_pct': 0.5029},
    {'ticker': 'MPL.AU', 'name': 'Medibank Private L', 'sector': 'Financials', 'weight_pct': 0.4933},
    {'ticker': 'NEM.AU', 'name': 'Newmont Corporatio', 'sector': 'Materials', 'weight_pct': 0.4882},
    {'ticker': 'JHX.AU', 'name': 'James Hardie Indus', 'sector': 'Materials', 'weight_pct': 0.4717},
    {'ticker': 'MIN.AU', 'name': 'Mineral Res Ltd', 'sector': 'Materials', 'weight_pct': 0.4633},
    {'ticker': 'XRO.AU', 'name': 'Xero Limited', 'sector': 'Information Technology', 'weight_pct': 0.4551},
    {'ticker': 'TLC.AU', 'name': 'Lottery Corporatio', 'sector': 'Consumer Discretionary', 'weight_pct': 0.4524},
    {'ticker': 'ALQ.AU', 'name': 'Als Limited', 'sector': 'Industrials', 'weight_pct': 0.4259},
    {'ticker': 'NXT.AU', 'name': 'Nextdc Ltd', 'sector': 'Information Technology', 'weight_pct': 0.421},
    {'ticker': 'CHC.AU', 'name': 'Charter Hall Group', 'sector': 'Real Estate', 'weight_pct': 0.4071},
    {'ticker': 'ORI.AU', 'name': 'Orica Limited', 'sector': 'Materials', 'weight_pct': 0.4014},
    {'ticker': 'SGP.AU', 'name': 'Stockland', 'sector': 'Real Estate', 'weight_pct': 0.3903},
    {'ticker': 'CAR.AU', 'name': 'Car Group Ltd', 'sector': 'Communication Services', 'weight_pct': 0.3894},
    {'ticker': 'ASX.AU', 'name': 'Asx Ltd', 'sector': 'Financials', 'weight_pct': 0.3852},
    {'ticker': 'VCX.AU', 'name': 'Vicinity Centres', 'sector': 'Real Estate', 'weight_pct': 0.3799},
    {'ticker': 'LNW.AU', 'name': 'Light & Wonder Inc', 'sector': 'Consumer Discretionary', 'weight_pct': 0.3753},
    {'ticker': 'SFR.AU', 'name': 'Sandfire Resource', 'sector': 'Materials', 'weight_pct': 0.368},
    {'ticker': 'GPT.AU', 'name': 'Gpt Group', 'sector': 'Real Estate', 'weight_pct': 0.3583},
    {'ticker': 'SHL.AU', 'name': 'Sonic Healthcare', 'sector': 'Health Care', 'weight_pct': 0.3523},
    {'ticker': 'TNE.AU', 'name': 'Technology One', 'sector': 'Information Technology', 'weight_pct': 0.3485},
    {'ticker': 'PME.AU', 'name': 'Pro Medicus', 'sector': 'Health Care', 'weight_pct': 0.3441},
    {'ticker': 'QUB.AU', 'name': 'Qube Hldgs Ltd', 'sector': 'Industrials', 'weight_pct': 0.3248},
    {'ticker': 'JBH.AU', 'name': 'Jb Hi-Fi', 'sector': 'Consumer Discretionary', 'weight_pct': 0.3213},
    {'ticker': 'SGH.AU', 'name': 'Sgh Ltd', 'sector': 'Industrials', 'weight_pct': 0.3152},
    {'ticker': 'ALD.AU', 'name': 'Ampol Ltd', 'sector': 'Energy', 'weight_pct': 0.297},
    {'ticker': 'WTC.AU', 'name': 'Wisetech Global Lt', 'sector': 'Information Technology', 'weight_pct': 0.2913},
    {'ticker': 'GGP.AU', 'name': 'Greatland Resource', 'sector': 'Materials', 'weight_pct': 0.2792},
    {'ticker': 'PRU.AU', 'name': 'Perseus Mining Ltd', 'sector': 'Materials', 'weight_pct': 0.2776},
    {'ticker': 'AZJ.AU', 'name': 'Aurizon Holdings', 'sector': 'Industrials', 'weight_pct': 0.2774},
    {'ticker': 'REA.AU', 'name': 'Rea Group Limited', 'sector': 'Communication Services', 'weight_pct': 0.2733},
    {'ticker': 'RHC.AU', 'name': 'Ramsay Health Care', 'sector': 'Health Care', 'weight_pct': 0.2732},
    {'ticker': 'COH.AU', 'name': 'Cochlear Ltd', 'sector': 'Health Care', 'weight_pct': 0.2703},
    {'ticker': 'GMD.AU', 'name': 'Genesis Minerals', 'sector': 'Materials', 'weight_pct': 0.264},
    {'ticker': 'MGR.AU', 'name': 'Mirvac Group', 'sector': 'Real Estate', 'weight_pct': 0.2614},
    {'ticker': 'WHC.AU', 'name': 'Whitehaven Coal', 'sector': 'Energy', 'weight_pct': 0.2601},
    {'ticker': 'AMC.AU', 'name': 'Amcor Plc', 'sector': 'Materials', 'weight_pct': 0.2553},
    {'ticker': 'HUB.AU', 'name': 'Hub24 Limited', 'sector': 'Financials', 'weight_pct': 0.2477},
    {'ticker': 'DXS.AU', 'name': 'Dexus', 'sector': 'Real Estate', 'weight_pct': 0.234},
    {'ticker': 'BEN.AU', 'name': 'Bendigo & Adelaide', 'sector': 'Financials', 'weight_pct': 0.2321},
    {'ticker': 'DNL.AU', 'name': 'Dyno Nobel Limited', 'sector': 'Materials', 'weight_pct': 0.2314},
    {'ticker': 'RMS.AU', 'name': 'Ramelius Resources', 'sector': 'Materials', 'weight_pct': 0.2264},
    {'ticker': 'WOR.AU', 'name': 'Worley Limited', 'sector': 'Industrials', 'weight_pct': 0.2255},
    {'ticker': 'IGO.AU', 'name': 'Igo Ltd', 'sector': 'Materials', 'weight_pct': 0.2236},
    {'ticker': 'CMM.AU', 'name': 'Capricorn Metals L', 'sector': 'Materials', 'weight_pct': 0.2226},
    {'ticker': 'SDF.AU', 'name': 'Steadfast Group Li', 'sector': 'Financials', 'weight_pct': 0.2157},
    {'ticker': 'FPH.AU', 'name': 'Fisher & Paykel He', 'sector': 'Health Care', 'weight_pct': 0.209},
    {'ticker': 'VNT.AU', 'name': 'Ventia Services Gr', 'sector': 'Industrials', 'weight_pct': 0.2086},
    {'ticker': 'CWY.AU', 'name': 'Cleanaway Waste Mg', 'sector': 'Industrials', 'weight_pct': 0.2004},
    {'ticker': 'RRL.AU', 'name': 'Regis Resources Lt', 'sector': 'Materials', 'weight_pct': 0.1967},
    {'ticker': 'DOW.AU', 'name': 'Downer Edi Ltd', 'sector': 'Industrials', 'weight_pct': 0.1951},
    {'ticker': 'WGX.AU', 'name': 'Westgold Resources', 'sector': 'Materials', 'weight_pct': 0.1925},
    {'ticker': 'AGL.AU', 'name': 'Agl Energy', 'sector': 'Utilities', 'weight_pct': 0.1888},
    {'ticker': 'CDA.AU', 'name': 'Codan Ltd', 'sector': 'Information Technology', 'weight_pct': 0.1878},
    {'ticker': 'VAU.AU', 'name': 'Vault Minerals Ltd', 'sector': 'Materials', 'weight_pct': 0.1862},
    {'ticker': 'SEK.AU', 'name': 'Seek Limited', 'sector': 'Communication Services', 'weight_pct': 0.1854},
    {'ticker': 'EDV.AU', 'name': 'Endeavour Group Lt', 'sector': 'Consumer Staples', 'weight_pct': 0.1851},
    {'ticker': 'ALX.AU', 'name': 'Atlas Arteria', 'sector': 'Industrials', 'weight_pct': 0.1811},
    {'ticker': 'CGF.AU', 'name': 'Challenger Limited', 'sector': 'Financials', 'weight_pct': 0.1776},
    {'ticker': 'SGM.AU', 'name': 'Sims Ltd', 'sector': 'Materials', 'weight_pct': 0.175},
    {'ticker': 'PDN.AU', 'name': 'Paladin Energy Ltd', 'sector': 'Energy', 'weight_pct': 0.1746},
    {'ticker': 'A2M.AU', 'name': 'The A2 Milk Co Ltd', 'sector': 'Consumer Staples', 'weight_pct': 0.1657},
    {'ticker': 'AAI.AU', 'name': 'Alcoa Corp', 'sector': 'Materials', 'weight_pct': 0.1647},
    {'ticker': 'APE.AU', 'name': 'Eagers Automotive', 'sector': 'Consumer Discretionary', 'weight_pct': 0.1645},
    {'ticker': 'XYZ.AU', 'name': 'Block Inc', 'sector': 'Financials', 'weight_pct': 0.1617},
    {'ticker': 'MP1.AU', 'name': 'Megaport Ltd', 'sector': 'Information Technology', 'weight_pct': 0.1617},
    {'ticker': 'ANN.AU', 'name': 'Ansell', 'sector': 'Health Care', 'weight_pct': 0.1604},
    {'ticker': 'AMP.AU', 'name': 'Amp Limited', 'sector': 'Financials', 'weight_pct': 0.1572},
    {'ticker': 'LTR.AU', 'name': 'Liontown Limited', 'sector': 'Materials', 'weight_pct': 0.1554},
    {'ticker': 'TLX.AU', 'name': 'Telix Pharmaceutic', 'sector': 'Health Care', 'weight_pct': 0.1532},
    {'ticker': 'BOQ.AU', 'name': 'Bank Of Queensland', 'sector': 'Financials', 'weight_pct': 0.1501},
    {'ticker': '360.AU', 'name': 'Life360 Inc.', 'sector': 'Information Technology', 'weight_pct': 0.1457},
    {'ticker': 'TWE.AU', 'name': 'Treasury Wine Esta', 'sector': 'Consumer Staples', 'weight_pct': 0.1437},
    {'ticker': 'REH.AU', 'name': 'Reece Limited', 'sector': 'Industrials', 'weight_pct': 0.1401},
    {'ticker': 'EMR.AU', 'name': 'Emerald Resources', 'sector': 'Materials', 'weight_pct': 0.1396},
    {'ticker': 'ZIP.AU', 'name': 'Zip Co Ltd', 'sector': 'Financials', 'weight_pct': 0.1359},
    {'ticker': 'WAF.AU', 'name': 'West African Res', 'sector': 'Materials', 'weight_pct': 0.1351},
    {'ticker': 'AUB.AU', 'name': 'Aub Group Limited', 'sector': 'Financials', 'weight_pct': 0.1317},
    {'ticker': 'MTS.AU', 'name': 'Metcash Limited', 'sector': 'Consumer Staples', 'weight_pct': 0.1299},
    {'ticker': 'CNU.AU', 'name': 'Chorus Ltd', 'sector': 'Communication Services', 'weight_pct': 0.1288},
    {'ticker': 'ILU.AU', 'name': 'Iluka Resources', 'sector': 'Materials', 'weight_pct': 0.1255},
    {'ticker': 'NWH.AU', 'name': 'Nrw Holdings Ltd', 'sector': 'Industrials', 'weight_pct': 0.1242},
    {'ticker': 'PDI.AU', 'name': 'Predictive Discove', 'sector': 'Materials', 'weight_pct': 0.1232},
    {'ticker': 'NHF.AU', 'name': 'Nib Holdings Ltd', 'sector': 'Financials', 'weight_pct': 0.1216},
    {'ticker': 'BRG.AU', 'name': 'Breville Group Ltd', 'sector': 'Consumer Discretionary', 'weight_pct': 0.1203},
    {'ticker': 'PNI.AU', 'name': 'Pinnacle Inv Mgmt', 'sector': 'Financials', 'weight_pct': 0.1184},
    {'ticker': 'CSC.AU', 'name': 'Capstone Copper Co', 'sector': 'Materials', 'weight_pct': 0.1095},
    {'ticker': 'RWC.AU', 'name': 'Reliance Worldwide', 'sector': 'Industrials', 'weight_pct': 0.1093},
    {'ticker': 'MND.AU', 'name': 'Monadelphous Group', 'sector': 'Industrials', 'weight_pct': 0.1074},
    {'ticker': 'NHC.AU', 'name': 'New Hope Corp', 'sector': 'Energy', 'weight_pct': 0.1061},
    {'ticker': 'DBI.AU', 'name': 'Dalrymple Bay Infr', 'sector': 'Industrials', 'weight_pct': 0.1049},
    {'ticker': 'HVN.AU', 'name': 'Harvey Norman Hldg', 'sector': 'Consumer Discretionary', 'weight_pct': 0.1015},
    {'ticker': 'NWL.AU', 'name': 'Netwealth Group', 'sector': 'Financials', 'weight_pct': 0.1012},
    {'ticker': 'RGN.AU', 'name': 'Region Re Ltd', 'sector': 'Real Estate', 'weight_pct': 0.0986},
    {'ticker': 'VEA.AU', 'name': 'Viva Energy Group', 'sector': 'Energy', 'weight_pct': 0.0979},
    {'ticker': 'RSG.AU', 'name': 'Resolute Mining', 'sector': 'Materials', 'weight_pct': 0.0923},
    {'ticker': 'SRG.AU', 'name': 'Srg Global Ltd', 'sector': 'Industrials', 'weight_pct': 0.0918},
    {'ticker': 'CLW.AU', 'name': 'Charter Hall Long', 'sector': 'Real Estate', 'weight_pct': 0.091},
    {'ticker': 'DRO.AU', 'name': 'Droneshield Ltd', 'sector': 'Industrials', 'weight_pct': 0.0903},
    {'ticker': 'FLT.AU', 'name': 'Flight Centre Trav', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0888},
    {'ticker': 'YAL.AU', 'name': 'Yancoal Australia', 'sector': 'Energy', 'weight_pct': 0.0873},
    {'ticker': 'NIC.AU', 'name': 'Nickel Industries', 'sector': 'Materials', 'weight_pct': 0.0866},
    {'ticker': 'HDN.AU', 'name': 'Homeco Daily Needs', 'sector': 'Real Estate', 'weight_pct': 0.0859},
    {'ticker': 'BWP.AU', 'name': 'Bwp Group', 'sector': 'Real Estate', 'weight_pct': 0.0855},
    {'ticker': 'BGL.AU', 'name': 'Bellevue Gold Ltd', 'sector': 'Materials', 'weight_pct': 0.0845},
    {'ticker': 'AIA.AU', 'name': 'Auckland Intl', 'sector': 'Industrials', 'weight_pct': 0.0831},
    {'ticker': 'SUL.AU', 'name': 'Super Retail Group', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0773},
    {'ticker': 'IMD.AU', 'name': 'Imdex Ltd', 'sector': 'Materials', 'weight_pct': 0.076},
    {'ticker': 'TAH.AU', 'name': 'Tabcorp Holdings L', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0758},
    {'ticker': 'DRR.AU', 'name': 'Deterra Royalties', 'sector': 'Materials', 'weight_pct': 0.0736},
    {'ticker': 'CQR.AU', 'name': 'Charter Hall Retai', 'sector': 'Real Estate', 'weight_pct': 0.0718},
    {'ticker': 'OBM.AU', 'name': 'Ora Banda Mining L', 'sector': 'Materials', 'weight_pct': 0.0717},
    {'ticker': 'PRN.AU', 'name': 'Perenti Limited', 'sector': 'Materials', 'weight_pct': 0.0716},
    {'ticker': 'ORA.AU', 'name': 'Orora Ltd', 'sector': 'Materials', 'weight_pct': 0.0711},
    {'ticker': 'MSB.AU', 'name': 'Mesoblast Ltd', 'sector': 'Health Care', 'weight_pct': 0.071},
    {'ticker': 'LLC.AU', 'name': 'Lendlease Corp Ltd', 'sector': 'Real Estate', 'weight_pct': 0.07},
    {'ticker': 'CNI.AU', 'name': 'Centuria Capital G', 'sector': 'Real Estate', 'weight_pct': 0.0674},
    {'ticker': 'ALK.AU', 'name': 'Alkane Resources', 'sector': 'Materials', 'weight_pct': 0.0661},
    {'ticker': '4DX.AU', 'name': '4D Medical Ltd', 'sector': 'Health Care', 'weight_pct': 0.0659},
    {'ticker': 'PPT.AU', 'name': 'Perpetual Limited', 'sector': 'Financials', 'weight_pct': 0.0646},
    {'ticker': 'NEU.AU', 'name': 'Neuren Pharmaceuti', 'sector': 'Health Care', 'weight_pct': 0.0632},
    {'ticker': 'JDO.AU', 'name': 'Judo Capital Hldgs', 'sector': 'Financials', 'weight_pct': 0.0629},
    {'ticker': 'NXG.AU', 'name': 'Nexgen Energy Ltd', 'sector': 'Energy', 'weight_pct': 0.0627},
    {'ticker': 'MFG.AU', 'name': 'Magellan Financial', 'sector': 'Financials', 'weight_pct': 0.0624},
    {'ticker': 'CIP.AU', 'name': 'Centuria Industria', 'sector': 'Real Estate', 'weight_pct': 0.0621},
    {'ticker': 'ARB.AU', 'name': 'Arb Corporation.', 'sector': 'Consumer Discretionary', 'weight_pct': 0.061},
    {'ticker': 'TPG.AU', 'name': 'Tpg Telecom Ltd', 'sector': 'Communication Services', 'weight_pct': 0.0607},
    {'ticker': 'DYL.AU', 'name': 'Deep Yellow Ltd', 'sector': 'Energy', 'weight_pct': 0.0601},
    {'ticker': 'BGA.AU', 'name': 'Bega Cheese Ltd', 'sector': 'Consumer Staples', 'weight_pct': 0.0588},
    {'ticker': 'CYL.AU', 'name': 'Catalyst Metals Lt', 'sector': 'Materials', 'weight_pct': 0.0585},
    {'ticker': 'INA.AU', 'name': 'Ingenia Communitie', 'sector': 'Real Estate', 'weight_pct': 0.0578},
    {'ticker': 'CIA.AU', 'name': 'Champion Iron Ltd', 'sector': 'Materials', 'weight_pct': 0.0577},
    {'ticker': 'BPT.AU', 'name': 'Beach Energy Ltd', 'sector': 'Energy', 'weight_pct': 0.0572},
    {'ticker': 'LOV.AU', 'name': 'Lovisa Hldgs Ltd', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0569},
    {'ticker': 'NWS.AU', 'name': 'News Corp New', 'sector': 'Communication Services', 'weight_pct': 0.0555},
    {'ticker': 'SLC.AU', 'name': 'Superloop Ltd', 'sector': 'Communication Services', 'weight_pct': 0.0551},
    {'ticker': 'DTL.AU', 'name': 'Data 3 Ltd', 'sector': 'Information Technology', 'weight_pct': 0.0549},
    {'ticker': 'ARF.AU', 'name': 'Arena Reit', 'sector': 'Real Estate', 'weight_pct': 0.0547},
    {'ticker': 'WPR.AU', 'name': 'Waypoint Reit', 'sector': 'Real Estate', 'weight_pct': 0.0534},
    {'ticker': 'VUL.AU', 'name': 'Vulcan Energy Reso', 'sector': 'Materials', 'weight_pct': 0.052},
    {'ticker': 'PMV.AU', 'name': 'Premier Invs', 'sector': 'Consumer Discretionary', 'weight_pct': 0.052},
    {'ticker': 'IFT.AU', 'name': 'Infratil Ltd', 'sector': 'Financials', 'weight_pct': 0.0517},
    {'ticker': 'IPX.AU', 'name': 'Iperionx Ltd', 'sector': 'Materials', 'weight_pct': 0.0514},
    {'ticker': 'SLX.AU', 'name': 'Silex Systems', 'sector': 'Industrials', 'weight_pct': 0.0505},
    {'ticker': 'ASB.AU', 'name': 'Austal Limited', 'sector': 'Industrials', 'weight_pct': 0.0501},
    {'ticker': 'PXA.AU', 'name': 'Pexa Group Ltd', 'sector': 'Real Estate', 'weight_pct': 0.0492},
    {'ticker': 'HLI.AU', 'name': 'Helia Group Ltd', 'sector': 'Financials', 'weight_pct': 0.0491},
    {'ticker': 'NEC.AU', 'name': 'Nine Entertainment', 'sector': 'Communication Services', 'weight_pct': 0.0486},
    {'ticker': 'NCK.AU', 'name': 'Nick Scali', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0479},
    {'ticker': 'GDG.AU', 'name': 'Generation Develop', 'sector': 'Financials', 'weight_pct': 0.0474},
    {'ticker': 'EVT.AU', 'name': 'Evt Limited', 'sector': 'Communication Services', 'weight_pct': 0.0462},
    {'ticker': 'GNC.AU', 'name': 'Graincorp', 'sector': 'Consumer Staples', 'weight_pct': 0.0439},
    {'ticker': 'IRE.AU', 'name': 'Iress Limited', 'sector': 'Information Technology', 'weight_pct': 0.0426},
    {'ticker': 'ELD.AU', 'name': 'Elders Limited', 'sector': 'Consumer Staples', 'weight_pct': 0.0421},
    {'ticker': 'DMP.AU', 'name': 'Dominos Pizza Ent', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0416},
    {'ticker': 'WEB.AU', 'name': 'Web Travel Gp Ltd', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0414},
    {'ticker': 'ABB.AU', 'name': 'Aussie Broadband L', 'sector': 'Communication Services', 'weight_pct': 0.0408},
    {'ticker': 'KAR.AU', 'name': 'Karoon Energy Ltd', 'sector': 'Energy', 'weight_pct': 0.0392},
    {'ticker': 'PNR.AU', 'name': 'Pantoro Gold Ltd', 'sector': 'Materials', 'weight_pct': 0.0379},
    {'ticker': 'FBU.AU', 'name': 'Fletcher Building', 'sector': 'Industrials', 'weight_pct': 0.0375},
    {'ticker': 'SDR.AU', 'name': 'Siteminder Ltd', 'sector': 'Information Technology', 'weight_pct': 0.0362},
    {'ticker': 'CTD.AU', 'name': 'Corporate Travel', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0342},
    {'ticker': 'GQG.AU', 'name': 'Gqg Partners Inc.', 'sector': 'Financials', 'weight_pct': 0.034},
    {'ticker': 'GYG.AU', 'name': 'Guzman Y Gomez Ltd', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0319},
    {'ticker': 'IEL.AU', 'name': 'Idp Education Ltd', 'sector': 'Consumer Discretionary', 'weight_pct': 0.0244},
    {'ticker': 'TUA.AU', 'name': 'Tuas Ltd', 'sector': 'Communication Services', 'weight_pct': 0.0238},
    {'ticker': 'TPW.AU', 'name': 'Temple & Webster G', 'sector': 'Consumer Discretionary', 'weight_pct': 0.018},
]

if __name__ == "__main__":
    print(f"Total companies in ASX 200 watchlist: {len(ASX_200_WATCHLIST)}")
    for company in ASX_200_WATCHLIST[:10]:
        print(f"  {company['ticker']:>10}  {company['name']:<25}  {company['sector']}")
